require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ForumTopicsController do

  # This should return the minimal set of attributes required to create a valid
  # ForumTopic. As you add validations to ForumTopic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "forum" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ForumTopicsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all forum_topics as @forum_topics" do
      forum_topic = ForumTopic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:forum_topics).should eq([forum_topic])
    end
  end

  describe "GET show" do
    it "assigns the requested forum_topic as @forum_topic" do
      forum_topic = ForumTopic.create! valid_attributes
      get :show, {:id => forum_topic.to_param}, valid_session
      assigns(:forum_topic).should eq(forum_topic)
    end
  end

  describe "GET new" do
    it "assigns a new forum_topic as @forum_topic" do
      get :new, {}, valid_session
      assigns(:forum_topic).should be_a_new(ForumTopic)
    end
  end

  describe "GET edit" do
    it "assigns the requested forum_topic as @forum_topic" do
      forum_topic = ForumTopic.create! valid_attributes
      get :edit, {:id => forum_topic.to_param}, valid_session
      assigns(:forum_topic).should eq(forum_topic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ForumTopic" do
        expect {
          post :create, {:forum_topic => valid_attributes}, valid_session
        }.to change(ForumTopic, :count).by(1)
      end

      it "assigns a newly created forum_topic as @forum_topic" do
        post :create, {:forum_topic => valid_attributes}, valid_session
        assigns(:forum_topic).should be_a(ForumTopic)
        assigns(:forum_topic).should be_persisted
      end

      it "redirects to the created forum_topic" do
        post :create, {:forum_topic => valid_attributes}, valid_session
        response.should redirect_to(ForumTopic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved forum_topic as @forum_topic" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForumTopic.any_instance.stub(:save).and_return(false)
        post :create, {:forum_topic => { "forum" => "invalid value" }}, valid_session
        assigns(:forum_topic).should be_a_new(ForumTopic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForumTopic.any_instance.stub(:save).and_return(false)
        post :create, {:forum_topic => { "forum" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested forum_topic" do
        forum_topic = ForumTopic.create! valid_attributes
        # Assuming there are no other forum_topics in the database, this
        # specifies that the ForumTopic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ForumTopic.any_instance.should_receive(:update).with({ "forum" => "" })
        put :update, {:id => forum_topic.to_param, :forum_topic => { "forum" => "" }}, valid_session
      end

      it "assigns the requested forum_topic as @forum_topic" do
        forum_topic = ForumTopic.create! valid_attributes
        put :update, {:id => forum_topic.to_param, :forum_topic => valid_attributes}, valid_session
        assigns(:forum_topic).should eq(forum_topic)
      end

      it "redirects to the forum_topic" do
        forum_topic = ForumTopic.create! valid_attributes
        put :update, {:id => forum_topic.to_param, :forum_topic => valid_attributes}, valid_session
        response.should redirect_to(forum_topic)
      end
    end

    describe "with invalid params" do
      it "assigns the forum_topic as @forum_topic" do
        forum_topic = ForumTopic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForumTopic.any_instance.stub(:save).and_return(false)
        put :update, {:id => forum_topic.to_param, :forum_topic => { "forum" => "invalid value" }}, valid_session
        assigns(:forum_topic).should eq(forum_topic)
      end

      it "re-renders the 'edit' template" do
        forum_topic = ForumTopic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForumTopic.any_instance.stub(:save).and_return(false)
        put :update, {:id => forum_topic.to_param, :forum_topic => { "forum" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested forum_topic" do
      forum_topic = ForumTopic.create! valid_attributes
      expect {
        delete :destroy, {:id => forum_topic.to_param}, valid_session
      }.to change(ForumTopic, :count).by(-1)
    end

    it "redirects to the forum_topics list" do
      forum_topic = ForumTopic.create! valid_attributes
      delete :destroy, {:id => forum_topic.to_param}, valid_session
      response.should redirect_to(forum_topics_url)
    end
  end

end
